version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: vaccine-frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

  backend:
    build: ./backend
    container_name: vaccine-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres
    container_name: vaccine-database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fX7zLm82QpKe91YvBtNcAGhJrwZUXMbdHTvq043y
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules:
